#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly ROOT_DIR
readonly BUILD_DIR="${BUILD_DIR:-${ROOT_DIR}/build-r39}"
readonly RESULT_DIR="${RESULT_DIR:-${ROOT_DIR}/results/p1-mig-$(date -u +%Y%m%dT%H%M%SZ)}"
readonly STATE_DIR="${STATE_DIR:-/tmp/jdg-mps-1g}"
readonly SAMPLES="${SAMPLES:-1000}"
readonly WARMUP="${WARMUP:-100}"
readonly PRESSURE_SECONDS="${PRESSURE_SECONDS:-5}"
readonly CUDA_LIB="/usr/local/cuda-13.2/lib64"

sudo_cmd() {
  if [[ -n "${SUDO_PASSWORD:-}" ]]; then
    printf '%s\n' "${SUDO_PASSWORD}" | sudo -S -p '' "$@"
  else
    sudo "$@"
  fi
}

"${ROOT_DIR}/scripts/configure_thor_mig.sh"
# Generated by configure_thor_mig.sh.
# shellcheck disable=SC1091
source "${STATE_DIR}/mig.env"
mkdir -p "${RESULT_DIR}"

restore_graphics() {
  sudo_cmd systemctl start gdm3 >/dev/null 2>&1 || true
}
trap restore_graphics EXIT INT TERM
sudo_cmd systemctl stop gdm3

run_critical() {
  local output="$1"
  CUDA_VISIBLE_DEVICES="${JDG_MIG_BIG_UUID}" \
  LD_LIBRARY_PATH="${CUDA_LIB}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" \
    "${BUILD_DIR}/jdg-bench" --background none --samples "${SAMPLES}" \
      --warmup "${WARMUP}" >"${output}.tmp"
  mv "${output}.tmp" "${output}"
}

run_pair() {
  local mode="$1"
  CUDA_VISIBLE_DEVICES="${JDG_MIG_SMALL_UUID}" \
  CUDA_MPS_PIPE_DIRECTORY="${JDG_MPS_PIPE_DIRECTORY}" \
  CUDA_MPS_LOG_DIRECTORY="${JDG_MPS_LOG_DIRECTORY}" \
  LD_LIBRARY_PATH="${CUDA_LIB}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" \
    "${BUILD_DIR}/jdg-bench" --role pressure --background "${mode}" \
      --duration-seconds "${PRESSURE_SECONDS}" \
      >"${RESULT_DIR}/${mode}-pressure.json" &
  local pressure_pid=$!
  sleep 1
  run_critical "${RESULT_DIR}/${mode}.json"
  wait "${pressure_pid}"
}

cat /etc/nv_tegra_release >"${RESULT_DIR}/nv_tegra_release.txt"
nvidia-smi -q >"${RESULT_DIR}/nvidia-smi.txt"
"${ROOT_DIR}/scripts/probe_mig.sh" >"${RESULT_DIR}/mig.json"

run_critical "${RESULT_DIR}/isolated.json"
run_pair compute
run_pair memory

python3 "${ROOT_DIR}/analysis/summarize_mig.py" "${RESULT_DIR}" \
  >"${RESULT_DIR}/summary.json.tmp"
mv "${RESULT_DIR}/summary.json.tmp" "${RESULT_DIR}/summary.json"
printf 'P1 MIG results: %s\n' "${RESULT_DIR}"
