#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly ROOT_DIR
readonly BUILD_DIR="${BUILD_DIR:-${ROOT_DIR}/build-r39}"
readonly RESULT_DIR="${RESULT_DIR:-${ROOT_DIR}/results/p3-mig-matrix-$(date -u +%Y%m%dT%H%M%SZ)}"
readonly SMALL_STATE_DIR="${SMALL_STATE_DIR:-/tmp/jdg-mps-1g}"
readonly BIG_STATE_DIR="${BIG_STATE_DIR:-/tmp/jdg-mps-2g}"
readonly CUDA_LIB="/usr/local/cuda-13.2/lib64"
readonly SAMPLES="${SAMPLES:-100000}"
readonly WARMUP="${WARMUP:-1000}"
readonly PRESSURE_SECONDS="${PRESSURE_SECONDS:-8}"
telemetry_pid=""
big_mps_started=0

sudo_cmd() {
  if [[ -n "${SUDO_PASSWORD:-}" ]]; then
    printf '%s\n' "${SUDO_PASSWORD}" | sudo -S -p '' "$@"
  else
    sudo "$@"
  fi
}

stop_big_mps() {
  if [[ "${big_mps_started}" -eq 1 ]]; then
    printf 'quit\n' | env CUDA_MPS_PIPE_DIRECTORY="${BIG_STATE_DIR}/pipe" \
      CUDA_MPS_LOG_DIRECTORY="${BIG_STATE_DIR}/log" \
      nvidia-cuda-mps-control >/dev/null 2>&1 || true
    big_mps_started=0
  fi
}

cleanup() {
  local status=$?
  trap - EXIT INT TERM
  stop_big_mps
  if [[ -n "${telemetry_pid}" ]]; then
    kill -TERM "${telemetry_pid}" >/dev/null 2>&1 || true
    wait "${telemetry_pid}" >/dev/null 2>&1 || true
  fi
  sudo_cmd systemctl start gdm3 >/dev/null 2>&1 || true
  exit "${status}"
}
trap cleanup EXIT INT TERM

SUDO_PASSWORD="${SUDO_PASSWORD:-}" "${ROOT_DIR}/scripts/configure_thor_mig.sh"
# Generated by configure_thor_mig.sh.
# shellcheck disable=SC1091
source "${SMALL_STATE_DIR}/mig.env"
mkdir -p "${RESULT_DIR}" "${BIG_STATE_DIR}/pipe" "${BIG_STATE_DIR}/log"
sudo_cmd systemctl stop gdm3
sudo_cmd jetson_clocks

cat /etc/nv_tegra_release >"${RESULT_DIR}/nv_tegra_release.txt"
nvidia-smi -q >"${RESULT_DIR}/nvidia-smi.txt"
sudo_cmd jetson_clocks --show >"${RESULT_DIR}/jetson-clocks.txt" 2>&1 || true
tegrastats --interval 100 >"${RESULT_DIR}/tegrastats.txt" 2>&1 &
telemetry_pid=$!

common_args=(--samples "${SAMPLES}" --warmup "${WARMUP}" --background none)

run_critical() {
  local output="$1"
  shift
  env LD_LIBRARY_PATH="${CUDA_LIB}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" \
    "$@" "${BUILD_DIR}/jdg-bench" "${common_args[@]}" >"${output}.tmp"
  mv "${output}.tmp" "${output}"
}

run_pair() {
  local name="$1"
  local mode="$2"
  local pressure_uuid="$3"
  local pressure_pipe="$4"
  local pressure_log="$5"
  local quota="$6"
  local critical_pipe="$7"
  local critical_log="$8"
  local pressure_env=(CUDA_VISIBLE_DEVICES="${pressure_uuid}")
  local critical_env=(CUDA_VISIBLE_DEVICES="${JDG_MIG_BIG_UUID}")
  if [[ -n "${pressure_pipe}" ]]; then
    pressure_env+=(CUDA_MPS_PIPE_DIRECTORY="${pressure_pipe}"
                  CUDA_MPS_LOG_DIRECTORY="${pressure_log}"
                  CUDA_MPS_ACTIVE_THREAD_PERCENTAGE="${quota}")
  fi
  if [[ -n "${critical_pipe}" ]]; then
    critical_env+=(CUDA_MPS_PIPE_DIRECTORY="${critical_pipe}"
                  CUDA_MPS_LOG_DIRECTORY="${critical_log}")
  fi

  env LD_LIBRARY_PATH="${CUDA_LIB}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" \
    "${pressure_env[@]}" "${BUILD_DIR}/jdg-bench" --role pressure \
    --background "${mode}" --duration-seconds "${PRESSURE_SECONDS}" \
    >"${RESULT_DIR}/${name}-pressure.json" &
  local pressure_pid=$!
  sleep 1
  run_critical "${RESULT_DIR}/${name}.json" "${critical_env[@]}"
  wait "${pressure_pid}"
}

run_critical "${RESULT_DIR}/mig2g-isolated.json" \
  CUDA_VISIBLE_DEVICES="${JDG_MIG_BIG_UUID}"

for mode in compute memory; do
  run_pair "same-naive-${mode}" "${mode}" "${JDG_MIG_BIG_UUID}" "" "" \
    100 "" ""
done

# A direct warm-up ensures the 2g context exists only after the persistent 1g
# MPS context, satisfying the R39.2 context-order constraint.
run_critical "${RESULT_DIR}/mig2g-pre-mps-warm.json" \
  CUDA_VISIBLE_DEVICES="${JDG_MIG_BIG_UUID}"
find "${BIG_STATE_DIR}/pipe" -mindepth 1 -maxdepth 1 -delete
CUDA_VISIBLE_DEVICES="${JDG_MIG_BIG_UUID}" \
CUDA_MPS_PIPE_DIRECTORY="${BIG_STATE_DIR}/pipe" \
CUDA_MPS_LOG_DIRECTORY="${BIG_STATE_DIR}/log" nvidia-cuda-mps-control -d
big_mps_started=1

for quota in 25 50 100; do
  for mode in compute memory; do
    run_pair "same-mps-q${quota}-${mode}" "${mode}" \
      "${JDG_MIG_BIG_UUID}" "${BIG_STATE_DIR}/pipe" \
      "${BIG_STATE_DIR}/log" "${quota}" "${BIG_STATE_DIR}/pipe" \
      "${BIG_STATE_DIR}/log"
  done
done
stop_big_mps

for quota in 25 50 100; do
  for mode in compute memory; do
    run_pair "cross-mps-q${quota}-${mode}" "${mode}" \
      "${JDG_MIG_SMALL_UUID}" "${JDG_MPS_PIPE_DIRECTORY}" \
      "${JDG_MPS_LOG_DIRECTORY}" "${quota}" "" ""
  done
done

python3 "${ROOT_DIR}/analysis/summarize_mig_matrix.py" "${RESULT_DIR}" \
  >"${RESULT_DIR}/summary.json.tmp"
mv "${RESULT_DIR}/summary.json.tmp" "${RESULT_DIR}/summary.json"
printf 'P3 MIG matrix results: %s\n' "${RESULT_DIR}"
