#!/usr/bin/env python3
"""Generate preliminary paper tables from hash-validated P9 aggregates."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any, Iterable


SYSTEM_ORDER = (
    "NVIDIA MIG", "NVIDIA MPS", "Quota-only provisioning",
    "Partition-only planning", "Full-DAG quiescence", "QUIET",
)


def load(path: Path, kind: str) -> dict[str, Any]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    if raw.get("kind") != kind:
        raise ValueError(f"unexpected evidence kind: {path}")
    return raw


def latex_name(name: str) -> str:
    if name not in SYSTEM_ORDER:
        raise KeyError(name)
    return name


def generate(
    numeric_path: Path,
    structural_path: Path,
    transport_path: Path,
    plan_path: Path,
    heldout_path: Path,
) -> tuple[str, list[list[str]]]:
    numeric = load(numeric_path, "p9-numeric-mechanism-williams-aggregate")
    structural = load(structural_path, "p9-structural-limit-evidence")
    transport = load(transport_path, "p9-whisper-transport-williams-aggregate")
    plan = json.loads(plan_path.read_text(encoding="utf-8"))
    heldout = load(heldout_path, "p9-dependent-small-stress-smoke")
    systems = numeric.get("systems", {})
    if set(SYSTEM_ORDER) != set(systems):
        raise ValueError("numeric aggregate has unexpected public system rows")
    comparison = numeric.get("primary_feasible_comparison", {})
    if comparison.get("gain_supported") is not True:
        raise ValueError("QUIET/Orion paired gain is not supported")
    if structural.get("proposed_system") != "QUIET" or structural.get("transport", {}).get("balanced_raw_replay") is None:
        raise ValueError("structural evidence is incomplete")
    if plan.get("proposed_system") != "QUIET" or plan.get("status") != "selected":
        raise ValueError("QUIET slack plan is not selected")
    heldout_rows = heldout.get("results", [])
    if len(heldout_rows) != 1 or heldout_rows[0].get("system") != "QUIET":
        raise ValueError("held-out slack evidence is malformed")

    table_rows: list[list[str]] = []
    latex_rows: list[str] = []
    for name in SYSTEM_ORDER:
        row = systems[name]
        qualified = bool(row["same_slo_goodput_comparable"])
        display = latex_name(name)
        if name == "QUIET":
            display = f"\\textbf{{{display}}}"
        dmr = 100.0 * float(row["observed_dmr"])
        p99 = float(row["pooled_p99_us"])
        goodput = float(row["background_goodput_rps_mean"])
        marker = "yes" if qualified else "no"
        latex_rows.append(
            f"{display} & {int(row['requests']):,} & {dmr:.4f} & {p99:.2f} & {goodput:.2f} & {marker} \\\\"
        )
        table_rows.append([
            name, str(row["requests"]), f"{dmr:.6f}",
            f"{p99:.6f}", f"{goodput:.6f}", marker,
        ])

    paired = comparison["paired_ratio_mean_t95"]
    balanced = transport["systems"]
    selected = plan["selected_plan"]
    heldout_row = heldout_rows[0]
    tex = "\n".join([
        "% Generated by analysis/generate_p9_paper_tables.py; do not edit.",
        f"\\newcommand{{\\quietfullgategain}}{{{paired['mean']:.2f}$\\times$}}",
        f"\\newcommand{{\\quietfullgategainlow}}{{{paired['lower']:.2f}$\\times$}}",
        f"\\newcommand{{\\quietfullgategainhigh}}{{{paired['upper']:.2f}$\\times$}}",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\resizebox{\\linewidth}{!}{%",
        "\\begin{tabular}{lrrrrc}",
        "\\toprule",
        "Treatment & Requests & DMR (\\%) & p99 ($\\mu$s) & BE req/s & Same SLO \\\\",
        "\\midrule",
        *latex_rows,
        "\\bottomrule",
        "\\end{tabular}",
        "}%",
        "\\caption{Balanced P9 dependent-DAG mechanism evidence (six Williams sequences, 9,000 requests per treatment). Published-system names are reserved for native artifact ports and are not assigned to local ablations. This table is not thermal-normalized formal evidence.}",
        "\\label{tab:p9-dependent-performance}",
        "\\end{table}",
        "",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\resizebox{\\linewidth}{!}{%",
        "\\begin{tabular}{lrr}",
        "\\toprule",
        "Transport/placement & Edge p99 ($\\mu$s) & Pipeline p99 ($\\mu$s) \\\\",
        "\\midrule",
        f"Cross-MIG registered & {balanced['cross-mig-registered']['edge_p99_us']:.2f} & {balanced['cross-mig-registered']['pipeline_p99_us']:.2f}" + r" \\",
        f"Same-instance registered & {balanced['same-instance-registered']['edge_p99_us']:.2f} & {balanced['same-instance-registered']['pipeline_p99_us']:.2f}" + r" \\",
        f"Cross-MIG pinned bounce & {balanced['cross-mig-pinned']['edge_p99_us']:.2f} & {balanced['cross-mig-pinned']['pipeline_p99_us']:.2f}" + r" \\",
        f"Cross-MIG pageable bounce & {balanced['cross-mig-pageable']['edge_p99_us']:.2f} & {balanced['cross-mig-pageable']['pipeline_p99_us']:.2f}" + r" \\",
        "\\bottomrule",
        "\\end{tabular}",
        "}%",
        "\\caption{Raw-replayed 2.304-MB edge ablation (2,000 requests per treatment).}",
        "\\label{tab:p9-transport}",
        "\\end{table}",
        "",
        f"% Slack plan: reservation={selected['arrival_to_completion_reservation_us']:.3f} us, slack={selected['reserved_slack_us']:.3f} us.",
        f"% Held-out: misses={heldout_row['deadline_misses']}/{heldout_row['pipeline_requests']}, p99={heldout_row['pipeline_p99_us']:.3f} us, BE={heldout_row['background_goodput_rps']:.3f} req/s.",
        "",
    ])
    forbidden = ("mig-governor", "joint-governor", "jdg-governor")
    if any(value in tex for value in forbidden):
        raise ValueError("internal policy ID leaked into paper table")
    return tex, table_rows


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--numeric", type=Path, required=True)
    parser.add_argument("--structural", type=Path, required=True)
    parser.add_argument("--transport", type=Path, required=True)
    parser.add_argument("--plan", type=Path, required=True)
    parser.add_argument("--heldout", type=Path, required=True)
    parser.add_argument("--tex-output", type=Path, required=True)
    parser.add_argument("--csv-output", type=Path, required=True)
    args = parser.parse_args(argv)
    tex, rows = generate(
        args.numeric.resolve(), args.structural.resolve(), args.transport.resolve(),
        args.plan.resolve(), args.heldout.resolve(),
    )
    args.tex_output.parent.mkdir(parents=True, exist_ok=True)
    args.csv_output.parent.mkdir(parents=True, exist_ok=True)
    args.tex_output.write_text(tex, encoding="utf-8")
    with args.csv_output.open("w", newline="", encoding="utf-8") as output:
        writer = csv.writer(output)
        writer.writerow(("system", "requests", "dmr_percent", "p99_us", "background_goodput_rps", "same_slo"))
        writer.writerows(rows)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
