#!/usr/bin/env python3
"""Generate P9 Whisper paper tables from replay-verified evidence."""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from analysis.generate_p9_sota_tables import (  # noqa: E402
    FORBIDDEN_PRESENTATION_NAMES,
    SYSTEM_ORDER,
    format_rows,
    load_json,
    row_is_numeric,
)


def validate(
    aggregate: dict[str, Any], heldout: dict[str, Any], structural: dict[str, Any]
) -> None:
    if (
        aggregate.get("kind") != "p9-common-sota-williams-aggregate"
        or aggregate.get("scope") != "order-balanced-raw-replayed-nonthermal-campaign"
        or aggregate.get("workload") != "whisper-projection"
        or aggregate.get("proposed_system") != "QUIET"
    ):
        raise ValueError("Whisper common-workload contract differs")
    systems = aggregate.get("systems")
    if not isinstance(systems, dict) or tuple(systems) != SYSTEM_ORDER:
        raise ValueError("Whisper system order differs")
    if (
        heldout.get("kind") != "p9-quiet-frozen-plan-heldout-load-sweep"
        or heldout.get("workload") != "whisper-projection"
        or heldout.get("proposed_system") != "QUIET"
        or len(heldout.get("loads", [])) != 7
    ):
        raise ValueError("Whisper held-out contract differs")
    boundaries = structural.get("published_system_boundaries")
    if (
        structural.get("kind") != "p9-current-whisper-structural-evidence"
        or structural.get("proposed_system") != "QUIET"
        or not isinstance(boundaries, dict)
        or set(boundaries) != {"BOER", "ParvaGPU", "QUIET"}
        or boundaries["BOER"].get("independent_positive_control") is not True
        or boundaries["BOER"].get("dependent_feasible") is not False
        or boundaries["ParvaGPU"].get("independent_positive_control") is not True
        or boundaries["ParvaGPU"].get("dependent_feasible") is not False
    ):
        raise ValueError("Whisper structural-control contract differs")
    rendered = json.dumps((aggregate, heldout, structural), sort_keys=True)
    if any(name in rendered for name in FORBIDDEN_PRESENTATION_NAMES):
        raise ValueError("an internal policy identifier leaked into Whisper evidence")


def latex(
    aggregate: dict[str, Any], heldout: dict[str, Any], structural: dict[str, Any]
) -> str:
    validate(aggregate, heldout, structural)
    rows = format_rows(aggregate)
    boundaries = structural["published_system_boundaries"]
    boer = boundaries["BOER"]
    parva = boundaries["ParvaGPU"]
    # Older structural evidence records summary scalars rather than the
    # detailed positive-control selections.  Keep that evidence descriptive
    # instead of inventing served-rate numbers.
    boer_independent = boer.get("independent_selected")
    parva_services = parva.get("independent_services")
    if not isinstance(boer_independent, dict):
        boer_independent = {
            "worst_p99_ms": boer.get("best_measured_p99_ms"),
            "served_rps": [],
        }
    if not isinstance(parva_services, list):
        parva_services = []
    boer_rate = (
        f"{min(float(value) for value in boer_independent['served_rps']):.2f}"
        if boer_independent["served_rps"] else "--"
    )
    parva_p99 = (
        f"{max(float(item['p99_ms']) for item in parva_services):.3f}"
        if parva_services else "--"
    )
    parva_rate = (
        f"{min(float(item['served_rps']) for item in parva_services):.2f}"
        if parva_services else "--"
    )
    lines = [
        "% Generated by analysis/generate_p9_whisper_tables.py; do not edit.",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\caption{Large-payload dependent workload: Whisper Tiny's checksum-verified 2.304-MB activation feeds a TensorRT projection under a frozen $1{,}701.921$-$\\mu$s deadline. Each row contains 6,600 raw-replayed requests and is not thermally normalized.}",
        "\\label{tab:p9-sota-whisper}",
        "\\resizebox{\\columnwidth}{!}{%",
        "\\begin{tabular}{lrrrrr}",
        "\\toprule",
        "System & Misses & DMR (\\%) & p99 ($\\mu$s) & p99.9 ($\\mu$s) & BE req/s \\\\",
        "\\midrule",
    ]
    for row in rows:
        label = "\\textbf{QUIET}" if row["system"] == "QUIET" else row["system"]
        if not row_is_numeric(row):
            lines.append(f"{label} & \\multicolumn{{5}}{{c}}{{\\emph{{{row['status']}}}}} \\\\")
        else:
            lines.append(
                f"{label} & {row['misses']}/{row['requests']} & {row['dmr_percent']:.4f} & "
                f"{row['p99_us']:.2f} & {row['p999_us']:.2f} & "
                f"{row['background_goodput_rps']:.2f} \\\\"
            )
    lines.extend((
        "\\bottomrule",
        "\\end{tabular}%",
        "}",
        "\\end{table}",
        "",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\caption{Frozen-plan Whisper background-load characterization. The non-monotone 125-req/s outliers preclude a load-frontier claim without thermal repetition.}",
        "\\label{tab:p9-quiet-whisper-heldout}",
        "\\resizebox{\\columnwidth}{!}{%",
        "\\begin{tabular}{rrrrr}",
        "\\toprule",
        "Offered & Goodput & Misses & p99 ($\\mu$s) & Max ($\\mu$s) \\\\",
        "\\midrule",
    ))
    for row in heldout["loads"]:
        lines.append(
            f"{float(row['offered_rps']):.0f} & {float(row['background_goodput_rps']):.2f} & "
            f"{int(row['misses'])}/{int(row['requests'])} & {float(row['p99_us']):.2f} & "
            f"{float(row['maximum_us']):.2f} \\\\"
        )
    lines.extend((
        "\\bottomrule",
        "\\end{tabular}%",
        "}",
        "\\end{table}",
        "",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\caption{Provisioning-system positive controls and dependent-DAG outcomes. Both ports meet their 3-ms independent-service SLOs before the same abstractions fail under the frozen dependent workload.}",
        "\\label{tab:p9-provisioning-controls}",
        "\\resizebox{\\columnwidth}{!}{%",
        "\\begin{tabular}{lrrl}",
        "\\toprule",
        "System & Independent p99 (ms) & Served req/s & Dependent result \\\\",
        "\\midrule",
        f"BOER & {float(boer_independent['worst_p99_ms']):.3f} & {boer_rate} & "
        f"No feasible; best p99 {float(boer['best_measured_p99_ms']):.3f} ms \\\\ ",
        f"ParvaGPU & {parva_p99} & {parva_rate} & "
        "Producer admission infeasible \\\\ ",
        "\\bottomrule",
        "\\end{tabular}%",
        "}",
        "\\end{table}",
        "",
    ))
    return "\n".join(lines)


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--aggregate", type=Path, required=True)
    parser.add_argument("--heldout", type=Path, required=True)
    parser.add_argument("--structural", type=Path, required=True)
    parser.add_argument("--tex-output", type=Path, required=True)
    parser.add_argument("--csv-output", type=Path, required=True)
    args = parser.parse_args(argv)
    aggregate = load_json(args.aggregate)
    heldout = load_json(args.heldout)
    structural = load_json(args.structural)
    validate(aggregate, heldout, structural)
    args.tex_output.parent.mkdir(parents=True, exist_ok=True)
    args.tex_output.write_text(latex(aggregate, heldout, structural), encoding="utf-8")
    rows = format_rows(aggregate)
    args.csv_output.parent.mkdir(parents=True, exist_ok=True)
    with args.csv_output.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=tuple(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
